apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:dWpm9mA/Nv4gNYwG0BB053ayjWhHESws,iv:JDwi3nZ4S194MtXE24mp57IldFw3+yVMPu0FHLDSa3k=,tag:/srvdzKVSBlMTfG84415JQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:FIPUYO84O3HacnTNDnS6WuMxH7NKB/L6a0aPeydCXlD6oDDwVg==,iv:MhB/0iJQVJquc+jA/ZHMusSQaZktOoo+iVwD8uPzADg=,tag:ffNtEjeTCfKjDwY7OFfHqQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:vVtkreOHaXWsiW00pgxD,iv:dZK8BS9yOxonZlE1wXqZUk/urEtEDmtdamC3YCfRuSA=,tag:cZLzozo4m/Q3JnVipnHRpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVFNTUHcrNitrK0tBOVZH
            M3FCZ2NhbjR2MWYya1k1WXdYRXdkVXd5QXd3CkNqSGFLVEd4ZTZHZmdKbDZPZ3Js
            R2RsTXg0dTZBYlA3UU9jQjBmRXd3dVEKLS0tIHVxd0dKeVkxQThHU0F1YnJwYWkz
            cXF4SHFTclhzSkdqTkFxYW5hME1nbGsKJg1RY4yQqIqCAdIBesgzXjqsPISmdfPM
            pmLEPyUEg5iyl2r1cWArIOvWWNS/AodQtu0Ge58tXVjHC9vKfc13Ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-27T11:18:34Z"
    mac: ENC[AES256_GCM,data:wLHiGassMSGL2cr64Qvt7Lzt+3a3GHpAh2TXuYBzl1SK0zLtL9/n20a5nmAFIumYTXeqwy8y1VhcPHSxprJhWpc06rsV5crV3HwJgKe1lN1PK3WfBdAye2iY5Exm8dyhrAOBGWkS3PHVkhBaaRom7YcNZv4TdLyPeA9Net+iZWU=,iv:c0TmUCpa2u15wVtm1nhDage5NuX8pqRuPajU02Mf0HE=,tag:cQOt0F4pWyLSHLCBNU5UBA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
