apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:D3L+UhJyy9ZuXBxZSBRUGGPKENBwR2eH,iv:gX0fzGI+/hAHziq6rufRCqnkr9dN92+YEIunvXqVDiY=,tag:T6oixvdQ3eWOE6dEqwootA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:DNlgYF48Ivl9t3TMvsygUBvEHErlzBRCpeN3a/U+zHYb5NOLtQ==,iv:5QVkMxtQVRHhM1rmYtm3UKGv8l9U4M/LdpFPE+H5VvM=,tag:Fm+o9KOXX9heVlbulXdWkw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:uCwJWyj3vPDb5CFZATEV,iv:HFOv3xdAsgFTgaor5qPq82se569Zk7W1V+1mT1//rQ8=,tag:j2bI4SI0topPRR4R7T7iZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdFA2bGpNN3hDVTZyMEFS
            ejJGRFBneDM4cHBqcWVPbDQ5dlllemd0ejM4CnNhUXgweFkrWktlcDBLQnpOb0hr
            b3NPT3VhUVNic1lvYXJzZjhWS0pwYmsKLS0tIHZrQUhTWFlEODA5ckJCa3p0K2hu
            QWdqUmcvRVNjTjdOclJiOFRQM1lZc1UKUh2TPzv2KeV9PQGZ6JdmtTEAQENu+qlY
            5d9T76hFrO3nrMMr9nYqwSs6KQdtg1yVHz8dKr60n2Bq//TA837gTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-29T07:42:00Z"
    mac: ENC[AES256_GCM,data:3E1A33prqC+n9XFn8+0yFcDi1DpCQg28tGxmQ10WQmGpUmVLCSSXx3p19gOe+Ob/ZTqGzELQEFo5rfOQ6uyRyGArLw1TQlaBXbjbBZSa9pW1MFOrU10Qi4QaZz7FFdbZEzRt8SVysQHPeQIO3jol1HJ3+sFtT9K0zT11DI9Sxgk=,iv:QckRuRQgasv4/Tu6/P0ulfqLOWVUfvt9zAIF2ILEimg=,tag:hvPG4AYDcznNFUfXcPCUAw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
