apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:cyf40SAocQL5nstlwSjQLBQ6+sRodruO,iv:5zAI34a4aZ/NKgo0w88GxVECbJLJM5PNIcbe+uJLwKU=,tag:3PAHrsNVDnh2SKhi7pDJtQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:8/bD5B/LghEgPiugeX1YpmpWZujPLUr2lQ6RqBkwaaA9T3AOyA==,iv:8omYO4wNVnDACFQfrFvHDuGKU71ij28U1qV8nQc4/Hs=,tag:dAqFgvN4YAoPrIcufkOCvw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:VBvPCDBiqhiO3O+XYCBh,iv:P+DUflyMK6H+n01iuK54B8ZYvruaawrvzW7TUk6PpPk=,tag:Aa4V63473kYJ22BRLoQ/og==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQk91TUZ4VXkzTGs5UFh4
            MThvenp2TzBIRUhGbHJqUGxHT09sTHR2VFM4CklORksxMUFSUTVlRGlpRDdzYW9y
            cDc3ZS9wbzJLRjVrTWVXRC92amgvRmsKLS0tIE14c1dWMm1QV1Q5ckhSVnpsa3dZ
            KzVWL0RTL0VNTko5ZzJvMEJXS1F2dncKNPqDScX0w6QicH3pPjxcxqbdR7FTLOi4
            CpJt7iMVVZPjuZcW8Ox01PGpir+zv8F8JvqFS3c4LUOAvke4llEeyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-27T18:06:52Z"
    mac: ENC[AES256_GCM,data:Akiy6tKHgv9MECBC4ssfRF2ryXX//GiONqUFz5Mewx/dXxjdJWMqKkmGAKB/7qBQH4sP09VkDAeXI3x6AILJPOsanNQKS1FkEYAdeoYBPD63zLzJC75FTWV3Xz5mvn/FBdXzuTp6eY67rv0QASeZhQVeUO6bkwmAIKp7TdGbzJg=,iv:OYM0wRZ+TmVyq2aZmCsOdbBk02WEcvIHa5jrLSRFMzg=,tag:Qv5mwIP015arsoXJq6OMww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
