kind: ENC[AES256_GCM,data:ljEJiz/w,iv:DNRGjlrNyGdEhQ99MALjZZFj/ZW89xNCT9ITW1mFiXQ=,tag:TU5TsMTtVYxtWdQw4R70Bg==,type:str]
ansible_user: ENC[AES256_GCM,data:E90c3MLB6w==,iv:qu6JGsJbalbztxHtI8uJc7F8ZKT11SsU6K/Wu11h3bA=,tag:VpPDHYeL50yhVOtiAyorCw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:+cV/IX5HdkWRpj0tYNc1/Q==,iv:xbDS7jz8nbBB7ZAmB6IPrTq3xZ8PKe9BfKIejEmW1f8=,tag:S65/k45OfXzrBainHXxEdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVTFPWjJtSVA0RUhYSGtw
            em9LWjhadkhnVWJYMGlRYy9IMDFLV3U1QWpZCktKQzJQZHNWaGlpalVXbWRBUTBH
            a3JPZlEvOFVpandoR0pGOTYxWHR1RU0KLS0tIDliRmNFaDRKRFd1dmlwYXhoSGVj
            M2ovUWFZeE1uRG5qcGFWMllQR3BaV2sK2FSLQwPw3N2p9YNxZUncZNgLvzGJAI+L
            W4GGZxvp2GMUsdSrd8I66HlTVymzcCm3gDNCXYnoe+zbLYgObLNKuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-27T11:18:34Z"
    mac: ENC[AES256_GCM,data:udOwu9VAuGN+PJVHkByiW0nDYuxxmMcR3AWOk0TRmFm0kWeo+jGPLn4/fS+3C0PYQutmVkxAlO6iMORKvIo8VHhA8KVNcW6/a62DLYzSx50POFtjlCv+7XdrqxlsCdNbT4DEetfVS9dehg2T3bJwT6iuYWZYQAnRa85m/JQPCmE=,iv:A8mAkWccRdQgmxTsJdG2Ob/fo9zXpHaF72CAnc8aQ6o=,tag:htbEmzWLSiGLHB/zwsSR4A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
