kind: ENC[AES256_GCM,data:paBHkFYe,iv:WS1fEOYwJpkR8Z2oZxQhn0YQt7Y43kQBmlXgqopmPdE=,tag:g7TCv1UtOaXZh4f+j1sxzw==,type:str]
ansible_user: ENC[AES256_GCM,data:w55mN/e6CA==,iv:AXnDZwEWjGAJtCImwKiDt7dwFGGvrCUrK26SsIkCtTc=,tag:1w0W186XjAVU5+ItDBQ81w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Gd2bDuWYHviEX+ll2umzdA==,iv:kw/fBj+H9rUjCjIIXZPM+D0ItLXuAaURxCqRtLZkJCE=,tag:jmmY0WzRyHZcBAkdWkm2zQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdlYxaFArdWxjdGtEV3d1
            eWRiSVJaUHpqQWo4WTV4VUNsSTc4R3cyZkJnCnJ6ZVZEa1JZenltU2g2NThpVW1C
            Y2txZDFaOVN4amk1YU5oL2s0Mmh3bXcKLS0tIG5BN2NLcVhJNUxIZVNsOTlCZUg0
            ak5lQXp5UUYwL0xCb25vK0REODQrZW8KT5Aa2ssvdQNow1Z9CQjObI2sYT1Cva+q
            /GQHdKVRArI4aiZXR8ISp8cJdS+KXoAcFFHfkkSUR7kIhL/RRMEIkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-29T07:42:00Z"
    mac: ENC[AES256_GCM,data:D3ilD/3Ngg3q0zsc6tdG1zl3aOoBXIglAQUbRapulUG07j1rc5xCo2ALBWyGgAgseHQ1PU/NkhYGW32U7drqnqb7I6IMAW7X2E9qx9Zr32GiAXOrMQi1YJ73HKQkqHDsxIc/ydruOgMDmrUKvP4B6zRC/MP98gu2j/oNoVVf8yQ=,iv:MD3OfrP6heqURmmOLcLOjvQ8Z4AQvfe+i9fmYp0YMpA=,tag:aokmdyY6s8UdsInhbU9Vtw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
