kind: ENC[AES256_GCM,data:psJV3qAq,iv:4zr7bM3DA/uiFuUo7NUE+agZVFE2TJAz4Tm3quFUXoY=,tag:5ap35dVPhNyN7NiynGC2KQ==,type:str]
ansible_user: ENC[AES256_GCM,data:gtoSN+HmnQ==,iv:lACoETZRJ7n9EAn/I2i4tSLHfoz7qGZb/1Kb+9AwVKk=,tag:209bjw8fB1bRqfFIYA5Yow==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:KrFqSpcIFK5IefvWvmL4cg==,iv:P5VOVjjDedy7P8IlmjJH6W4DbbABkGhKhftsEspyiOQ=,tag:mv4WiIzIATr+u1gRDbf3nw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TVBSTWZhbHZwbVFvWUo0
            Z24vZ2xCbmRua3IrLzN2K2xiNGJTaU1lQzNjCnNWdklEV1hjWXhlMGtyVTA5Yzlh
            ZTJhTlpKQUNRbVJXNGYzdHQ0RDlmTEkKLS0tIDAxeU9tVGZMek1yN1dMM2M1M1pr
            VjJVVHVJa0E3TnhQMEkra0ZGUStvcDAKSbSPtGSQeyHdEzpKO0bZTjvzmUh/qGtY
            MYyTsMg2c2Vf4U/mPUie123a8l0guZGWW5RdtAwkp/Beov7ZMCDruQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-28T20:19:35Z"
    mac: ENC[AES256_GCM,data:9N3mBnaN38hFvPKWG/vuzq55VxIJEL4HGz2xhiyYIViPJHVPWOqipDT19O3OsSdu44CUuNkrk/yrscUaTA93Bw1v7P/CAyanOjm+n4nPw6OCZ9pVzJwwdTyFJWvCBTuZ8hrIEgL0+wkQAYQL1gBhLuDwEUVIplukm1reuZqYY+c=,iv:t5WNajbJSfv3tG1gU1HK0NP0iSug5cSs/bL95xzgLog=,tag:dp32/+kRE+k2DuXgJHcIKA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
