kind: ENC[AES256_GCM,data:PTMHkv5B,iv:NhhIBjSD9fiUejQSg3j4JSCNNb/gqW73nx570wsAsok=,tag:WoqV0RmkB6R47PL+bbu7QQ==,type:str]
ansible_user: ENC[AES256_GCM,data:/tRzKlUxPA==,iv:Dc26zOy/Ki6R9AuXDp4ja2N5sXNyYs7SiIzelRa89dE=,tag:x6dyg1ZnCSIjtC4cr2le3g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Q8z+/2SO5XStAyzTKrWS5w==,iv:a/RKebZLIqBfUJFrtxW4OV+VDQNuaxBFg8EdSzPeAnY=,tag:uLqQnKy3rVNG5tlN6TgijA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUU5uYTRNSmo1OUVoZnpS
            eFdod1FEeTJZS3p3d0RkTXVLS01wWVhzUkE0CkJlcUFqVlJVWURIaUJ4VXFwanpO
            TG13WFdmSzlwdW5NZk5YM3lQQmQvMUUKLS0tIG10WmdwcTEwNml5akJMQ3RJcFg5
            MTNUTVRHdFdsWWlyTWg3SmNpRmVIY1EKwkd1fQ1MbZjLVrrpYKw/h5AdNsZLJmUD
            +a2ERSLsVKUzCvXTvU6cTMXR8fRg8ddH/ss2HNhrEwyiubT+n0s90w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-27T18:06:52Z"
    mac: ENC[AES256_GCM,data:qEknse/FCaHbiaxp1qY8s8HnBt2ARuoOAnT3LENBYncz67IYVnU4c9l4/PGhU+RacFA9ru6KKds+nX5GWaZCWLYeUVc3iVgyVJ0MnWJORcgUMlSrwFPAk9hBUHOezR7cXMHEaDVPHidnb63Rly/8DW9XY0n7ri2bkyU+TrqHmOk=,iv:saP5Nrp/QBHE+J7FbETEZ0xbBiUqhLS/QFNYjwhWVXg=,tag:dGH3pUONgF/VNcm0Nx1yZQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
