kind: ENC[AES256_GCM,data:0UKolMJ9,iv:rsR8iIADPDdJn2/4Mjulp9ymmTIRkg8Rud+75t5TB1A=,tag:5RTtA+c2IcJ/2v/HnI7mgA==,type:str]
ansible_user: ENC[AES256_GCM,data:31Fe+qQl9w==,iv:/KW42jAI91puekeBwnexwN6pBVTge6xo876ph7dsIFM=,tag:hPWk961fXhn8MvXD1Z3Ssg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:AO9UQ7vpTHr1zr7LZpXt2w==,iv:mg2yUqZ/5HyReWJFxgS3jA/MUXPQFr8p4f3RcLTN67M=,tag:9OHAmilr31oacSz/ey6nIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQXRPcWZXa2JxcHhyancx
            MTI5eDlacDNIZGkycFhVN3MvYm5TQzJ5VkdNCnNsMG0wUzhVK3lwYkkvSGUyeWRG
            aU5xblB3UWNqMUI2YU5aQWUwNkphTkEKLS0tIGhnV041cUsvN2Jla1o3WUdnbTYx
            NHNrNWRNZHFTVkZzYm1PT0c5T0JIM3cK7LEGL75vW0BOvVPCgnoLziFbMiXXozn6
            wbUKdqcRtVNKbbvcbcw1lNcSH95RrnzqOzh0iGDEJqToeIolIzhNNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-28T20:19:35Z"
    mac: ENC[AES256_GCM,data:TD3zLfFdK0wRvG/8ysD66qZAtPXYhXpgv5ktfxV81nfBkgYMw0eMZMkrsIcoht7R+KK7Ca0MFNS8JgnsKTEKkOQQUhKzN+ABC6hyDX5CMM2cEgj8ys2cToC06KAB/K3Fr5sS2RF6Lg60m1OSobCIuedh2IyQGRaHefBJA8rtnPo=,iv:AqBvB0OQdTVNE2EkCfQDF1OZjCJ6+Q+5BMmBlVLCgvs=,tag:HFpqmUozIzmm/Tv5jzgxRw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
