kind: ENC[AES256_GCM,data:p7AfyR7I,iv:14I7+VM/TSzmm0GnPmzZt8y/RSFCDZUz3GPv52gyCL0=,tag:I5DtiePO+iUWiXa/NGBLZQ==,type:str]
ansible_user: ENC[AES256_GCM,data:ffp///Mbyg==,iv:b6S5bhwMiGGLdan0NrFzyhSY5z8FyJhios2e10CEryw=,tag:EyXUdRB09aXyk560FvKHCw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:lW3LR4j7TLzARgXiquDdSQ==,iv:Xaoc7bVLEqYJi3IxFQj/bnlFTRMBp0jXWzizjDOceJI=,tag:wllBpYAKqRtSUTu3gVJedA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RHFrNS9TcUhaUUV5NTlN
            aTY5aW80cEViZGJTTjh5MHBOc3hkelRrUTFRCjVpbW5BR2J2WmJINnZWV2tyZnZC
            cSt2SDFrdHpkZk5VMFVUMC9qZ3NHcGcKLS0tIHpVZmFONzNSMkpvZlpwazFVakVL
            YUJKODVBY1NRbmRnUHBHd3ZWQkF2WGcKPilaOwqqnPhs8A6g5w3uOrTenubDsmMa
            Kzzb1RFl7J8Mzlnq1yssdJ3VnSp6OFTvGZzKlQJBEIdvKYYow+pN9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-29T07:42:00Z"
    mac: ENC[AES256_GCM,data:IKHXAvSiCJwiH4ShtVzg7zECCuUIxn9v2D5pEkOH3wf8ibd8V8BK1Oo7ToRHGWgNXsCirYrMh2MJkvq6tp9Nbk1whYcNuNejX2sMqicjB2usJ/pIGEm6kZFsLK78+8F+BP3kEPQ5nKuP6anhFp2V6E7AUdGdz823xrVlxQXgOV4=,iv:5yv29wTzYuoS009Lp2R6tmWJqaB5BJVsYLp2Hv8wiDY=,tag:J7z1cSzBs6G+sUKRiB4nbQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
