kind: ENC[AES256_GCM,data:Tuif8gQj,iv:XER5T5LudBdPQxkPSpJbEIPNF6GBGFG1jjSH41H4MSs=,tag:lAcnNbnnNkkrKOBYFQWRLA==,type:str]
ansible_user: ENC[AES256_GCM,data:e0EM4CwuHg==,iv:MZzgCQ0jO7AD97vmDGzs38aypzVPti0I9HrkB9xMWBo=,tag:GQMGd0pNMfZTpkGGfz9/+g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:5CLNVvkdSnR4vYIMwm7DNQ==,iv:g6K6i90CQ/jxTTo8xy1jPwIlEBrHB1h77Lor7s/2S/M=,tag:mHe9N5DNE8+/ZNrPxJvUgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRlpseUFNRkN4Tlp6Qjgr
            bElXblA2VkFveUtpNndNeXNaTlZWSlZsQmxjCngwWldIWDRabkJ1TCtnbm9CMDVa
            T2x1WEQ3ZkNad3hlVHFucHN2ekJrRE0KLS0tIEVWbW10WTZHSmtzUm8vYkljUzRM
            aGFqSGJQZWlUMHVzZ3psNU4wOUFmUkkK0v2oClRmIbeHK66l1Z4mSnjr/xN1SHHY
            /3c1wR9Iji3gQ7pPWBviEa8HjgO0eSpP5HF1nooX7Yy7Ed5EejYiEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-29T07:42:00Z"
    mac: ENC[AES256_GCM,data:d75z9svwDX3wMtxg6EJGaRj0lQj1jexY7hSbBC0FiMRv7yBt9j3nJQHlZpNs/YI7Khq1IpIP5VtE2GDyPUPpcJhBWIyPijcmBDZXodKYFiXKjfArsYdHXiO+gGj0ZD9QCIBgRVMfImVlGIdL5y6aRFHU4zfFc4/qQIH9g81IQKA=,iv:F6mOdDeL1AJAIjXq+EXOmlNDz7suwaaHp2BhW+aUsmA=,tag:A5qyuH1W9gZtqZRPfFQbog==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
