kind: ENC[AES256_GCM,data:i3oQluBz,iv:JuR7uyyMZpuCUUGMcq3J75yH4FtvjcykSODD5obH9PY=,tag:n31pym4FXdxvNauLAc/isw==,type:str]
ansible_user: ENC[AES256_GCM,data:9bw/PwhS/g==,iv:dan451ZCY7z/4pYXWXS/E5ZdFvG3VGn4uxtyz/JEzSc=,tag:XH4I+i2cud7KApXRzeMXbQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Jj07GzGDEPs5fBGKJ/iWpg==,iv:ZrjqO9qNtJVlUcEuEJQarHXt6iyX6rc8stsGK0m2fWk=,tag:9utpk1zd4IYBG8Ht5QT7nA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWWRCRW1xQmhBRlhXTk1v
            SC96angvVWozNldkQVBWRng3Rk82RDZ1M2dzCjhocWVlUzFib0hCeUJTNXpWbU5S
            bVVvMnB6aVBEaUR0eldmbWtiZkNVdk0KLS0tIFZMeTI5UWpLbXhoeGIveXhJZDJv
            NmMrOEpVVnhYVVlVZzl4TTM0VnhoRmsKEKeyU7tX5VgsrdsWwLcd8+5F3Lt9bOl0
            SjS1iUw90vh6RS/0Atzix29+GhQNFxsUl8lWl1jbWCXiy/qrvqsFZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-27T11:18:34Z"
    mac: ENC[AES256_GCM,data:bYIHJijy3M3DeifDjr3M2puljoXHMg3nwistRj3lSJRPnc2iAwCojO+yw0ht30zjhTPAQrfVejhxkSG6s/UuK4RsYarZAsTpdrVgJ7lwJnElmAuYExplvx5OdAiocZ6mZ+KydvVj5KPxbtgLZoYKdRqHJx6vSdfHauy7qE+/+pQ=,iv:dewTojbsJ0cuQFrAhL7U3Edigakz0l8s/0yCeDXYI6c=,tag:pPnDEIBAXFYV79/GP7TKSg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
