kind: ENC[AES256_GCM,data:9g2P5rXV,iv:QxnUkI1ak/kxK5Xk9+/UqkQwYv292xd13ap44QW+drM=,tag:SyeYV4rgaQi/YusOTE4ziw==,type:str]
ansible_user: ENC[AES256_GCM,data:S1qwuDUk3A==,iv:EvAHEK8/fXNUF2+5H5sOkD/Zq4rmV8YKbln0KIW8byA=,tag:nlFH7ojUCMyZ4o7p83EijQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:h/TyDt5hWjM2HyQTfHm+kg==,iv:8D7tr/505yJbmorJ8bVOD4NAmfdKBUM8/brL/QMG68k=,tag:X+YdpFEguihXBQSz5d2PAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4QUhDb1FnZXVXUk9uQjFI
            QzNWS01rL2VRMk05d0F2RTlIN25CRTQ3UzF3CjVVRTZZck9EdG11T21DdjQzSVdW
            UWl0aFJISkczeUI3c3dDSVQ1SGxSRVkKLS0tIEk1QVhsOVQ5Wnd0U25wdHYvdEZ0
            OEZuQXo4YmNOQzNxZ1BBNVpTWDBVR2MKCF/9NL24/ZvCSP9eEY3q48MjrI8GbE+v
            zvB/bMfZXh5MssgIHY3WZ71L4o1Yn0XtxzicHSs/WHz2NtJJb9PKcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-27T11:18:34Z"
    mac: ENC[AES256_GCM,data:g5l7XPphWfNajCSXyWjAy/ROgWMBCOI3lgJ/sg+NC0Ir7FkEWFV7Omo1iGArl9zG/r2LfKTKcQvfGWbZEErPr+zhUEwPanz92aqIAIMx7pjkJs1qepgnsyGUYd362OuIemvxuiYgz2t/k/gr9w63g8WpByoeGv0NOOKlSnKN1HE=,iv:++X3n+FNkUpdGw/hsFq1ZViQeJv5I2OiywWjWaBRWoo=,tag:vhWm5aLV2AeUZyrnvODWpw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
