kind: ENC[AES256_GCM,data:VoNuzKNb,iv:WZbeMPSGnQZoVitfyq5CW6+WL9SHu8KU+2xObK0O8Zw=,tag:QdbKGTXcDwwHDpwZtNfylA==,type:str]
ansible_user: ENC[AES256_GCM,data:RF52dbtJIw==,iv:FYkh965yI9OlAvjnwKVfBYJ9D1oAsPCxx2s+ebfk0hg=,tag:pixkLfNqSWSBZ3lVL6o88Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:r83y1xvV610N8K0Qcb0AKw==,iv:WL80efrqrJSCerK+tfii74Z4BEXswItvpdUJj8/UmUc=,tag:Gykg1RAm2UhTXnqtsQRqog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Sm1UVG4ybFFlOFpJUGRL
            SVBraWxwVXZ6aFB6TE1rTG1VTlMrVVN6RDBnCmtuUzgwVTZ5SmxMb092QkRRdzcy
            VHVFcDFYMFFLRHFDOFhIM0EyL242VzQKLS0tIDFpRjR4bmRaekVaKzNsSlZQdVlM
            RTl6bHh6bU1TemVhU2JEUkJuMzJaaDgKR6eAMy+UbjI23cl1kTdEeikG1Y1G2s0Z
            fvmO+2/9FSKW2LqEHKyrqenffmCauTP/5OKv5fKBvZcAFrujYrmdlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-27T18:06:52Z"
    mac: ENC[AES256_GCM,data:rk53UHaRzYkn7ynXH04N4/BqvtePSpMKsXF+tveVY20J94IjXs952s0H9MBJAVp/Zh8E8+FwCX3lmzrAyT8Y5GaEU9ebcl7YJRxkNtnIDdkoGaBUey/ESDsUSo8P+yBjU3amwoy40ljZ7Ag34vS3xf4xPliLvUhoc4kLpLU3Ck8=,iv:rRw4F0FH+JtxvP52Cb8dl3P5Y1kA6vBIMH/YwebYvmw=,tag:jtHf8XM16CZJ01q0DLr9yA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
