kind: ENC[AES256_GCM,data:c26kXyzJ,iv:TbFoVuehgIJJk1Dn6hbsab4q9puGpbQD033UVuGEU6w=,tag:BH8dldYCkriPgz8e9xJ/4g==,type:str]
ansible_user: ENC[AES256_GCM,data:zcQ8tcRtRw==,iv:c+YSGUU7TzmuRuKRFZe3eROPNvl9Yn8uVl+PmezPQ68=,tag:IgD5ULL4gEXvtc0UHG+KGQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:tDawSL6u0lc9IPXSp+9Zeg==,iv:F6FP2aYcqUsJ5r06dxaZgxd2nyRIE+Q8obpw6LBmi4k=,tag:KWL3I7f1lswYHjgBICavBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRGw3QzFFcHNWc1QyUDlt
            cDRMR0hzb1dnV0hWb0NMTDMyb0RBZTlwS3kwClZ5NklmUTRMNzNRZnZPSjhzS29B
            cWtYZTJvRURzTlVwRWVnUDFkcU1YdncKLS0tIGc3T0RmMVBYRnNLcFJYS0Z2cHpE
            OHZJRC9CSVZxT29VNkU3M3N0WlVsMkUKXEgjDzdBSfZLtC9arwE2sHLB1MVVgdfK
            9SjBqF+DxeiIiMriqqpnW2jlRJ36PHC7Bmoe/0WQ+VGqefre7qyQEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-29T07:42:00Z"
    mac: ENC[AES256_GCM,data:R3YHdSRvgHXDdI6CeUARcWGRu/iWJxmQNfYa9V8BEcP6EPfujrHtT1wvYTlwkIybdW8F03I3di0S7MItGVPuGUtJtCqRco476pgIfTkZK/9bTELTLMTi9RgECZ9DYx70R1hxnwceMj4EVihQdwuvXBiLwINHBozQrWv2otCabGk=,iv:vDCZbK9M+p7603JYyMzyC+NZjcqRRYpqif4crBKDcjQ=,tag:TnLVMmMVu0M3lUaAduua4w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
