kind: ENC[AES256_GCM,data:aivLG/D3,iv:xyoEC0Df9eyg8QaaIb6BT+JkqKHyL2u41anlxtJcgyk=,tag:uSZQuiRn8XFtvHouHdZJsg==,type:str]
ansible_user: ENC[AES256_GCM,data:qFL8vw9kmw==,iv:n7NtADYWHiQgi00vLYohgJTkuXdZuDJScv/0Id5hFfU=,tag:0r0qK4QEg7lu2w6k2obR4A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:mRAZi0t4j945ZfTaXvtxvA==,iv:hFIQt+zyWLVBN+uXxdKcN32f4Bii9Cu4qK3wmb0CR5E=,tag:8a9A/bTKTHHZTcdK7V1jtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPelhyOWlUM0t5Y1lTOWpH
            SFlNVnRPUUNYS1JROFVjdlI2ZitUaDhGQWhzCjErUFhMZmRkR2tTeW9zdmF6dG1W
            cmVSN3FIRllnVjJQbTFQemVLRXl3Y2MKLS0tIGMvMUFMODlXQmhkSWQzT1I2TVM5
            WGN0V2Y1S2ViN0ZMVTc2Kzl0Unk1WTgKgToHYjH0Te7hLfV0box7G4UaDtaZYYcR
            nWVBMoxMFTs5QfK6I27Mocr2yh2NF83UCPloLzxo/UzerTbBHBvCEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-27T11:18:34Z"
    mac: ENC[AES256_GCM,data:BMMPO/YowI0XuEG7d+xA6FeASRx9YnyYCYH4s40kq3/8hiyEk9c/w+DwgaRFIV1aaR/wi+LIv+FLX6kufW5Izt8mlLsvWgtg1IKygfp3+Q/NE3GyK4E31Nc3QPZwoY2uobRArfPSIVyJr3x5hkyKcj9QSxX9HGQFameRI+ZMAn4=,iv:dYVyxzlylMtLvAvVMc5wi/ORcw5AegpFDS2InnZxXNo=,tag:v9SraL/O2lqpTQAYsCfRYA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
