kind: ENC[AES256_GCM,data:61xti5P4,iv:Cj+tP9G/nZ/ayd1TUwKjEAdMWYUMUaV5s2eFSmJGcWY=,tag:aDIStPt5TH9YVggwIyIbwQ==,type:str]
ansible_user: ENC[AES256_GCM,data:8fa/NfIBsA==,iv:R3DnEQztIDus2Z6XMHnWJZQV1aSTMvAaL4TDjHf83FY=,tag:X2GlPhZHrNIWfSrtuZ/CJA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:ZKsjS2tKblGTR9+eMl1wig==,iv:vhD9ULzzYT1b1SUF9WIaZewn2aaxi7BE5VnXC9ssFqI=,tag:xGH5Xk8HkFWx5/MfnQZ//w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRHZPaWtQNVVGR0xrbnRk
            YWRwb0xwMGZZZTZzVFpZdThURjdDYzZMcXdnClN0N2JEY0RDWGMyYzNhOTR3UUxs
            R2ZzR2NEYnlJN0YrM3ZpNmxZRUxEVk0KLS0tIFRBTm5mNVJOei9QY2JKZXFKZko2
            OERYWVRPSnJhZEJjUTlBSkJFMEJhdGcK7tNlWqnlsWDGQJFF8ixcBcs95WtlRgFX
            PwpT6D/3R14Qx4SGG0pN/C7ICvJ8BgvuTL7YXBR5I+kgGDLcNBD1Zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-28T20:19:35Z"
    mac: ENC[AES256_GCM,data:1nj/YY/SNHvn6AB2tzGo01cT2kML1gvU0u4iqDvYFydV+ou0Wp8hZ4uytNJlWsDn0Ps79DVvkMCwelDqaTeEp+xHX+Z7FuiqhtuMF/M/dhM4XX2fHc6D/tAh7LXkwR+a0QVnw2zghe3I6tWJy5kBYQSwwp3lS027Ut32qvo3r3c=,iv:pNzUX3RIqe91c3Xp8L8igfrQMEmvD8shZWn7wwZEPIw=,tag:Kb8BSWouUnl+nllF7+M+Jw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
