kind: ENC[AES256_GCM,data:yCZrvON9,iv:F24Mz69HNLEt+Cq8dQwIJdmdY+LDTX6nt6iGzpMJePc=,tag:9qulUbQMJr+IA7Z1EZArMA==,type:str]
ansible_user: ENC[AES256_GCM,data:8m22QbBUWw==,iv:YsgEKLcVG0gfCzpvE211ttdCaiqaxnHSav8Waw3QCWQ=,tag:o+VvgtDYAKUXTgNtwTR3mg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:9kkEl3DgDfba+ZGOUWbhmQ==,iv:72jKVAXa1yJYxxA/fsOirSeBK0gjZJV4ncVD+dEW7oA=,tag:m8aQdESwXczjbTH0ZFaUQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Y284VkIwWmtzOFBqZnhZ
            THpna0xEWTNuWTRLa0x0VWFXVFpkc2ZnbUE0CmcxN2pTQytxWk1zNTJrZWxuK1VY
            WTJweEtMYVZNSGZ3dS9YNk4xZlRuYmcKLS0tIFJpNldrdWVVU1B2K29jTmZ6a2h4
            QTRRQW1YeEt5cy9vT2I0bkF5Y01TZnMKC8VPWdlPcRc4qcWa4FXzBizvNV+4LHvf
            gY50Jwb2VD+L+VCuLhznotZ6Xq61VNCw88SOTc0M1XWrC+VkbUkS/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-29T07:42:00Z"
    mac: ENC[AES256_GCM,data:JvSKOolcl5qPwJYmAZ62JWqW+27NAHC7wigN+xwssIQFZNP9f+oMkI5Y6YtdXgeR3PEH7kcozbYoMp8tHKCD6diHFZwfKdizAcaLIwfQz+V1OEYqbfwmrQKz4ttWTJi1pBswjTW95a6LfQqUQMexVRBiUN5n6Z4EEFYSr+BB6pg=,iv:qExaSvNfZaLcGJgPKCWSfZs4OBZ1OR6bP09MWpgA4Dc=,tag:56GewB3JOMwoGcHJzPmPLQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
