kind: ENC[AES256_GCM,data:cQpSjRnq,iv:Hu90U+sc2JXmVxMHR/M40rSN50VBxwnko398MNDUbx8=,tag:MsAqgXxlp0YA1V6YMB1tfA==,type:str]
ansible_user: ENC[AES256_GCM,data:UFzqFsjfSA==,iv:hJK5g7KX3LgFOburTg5JZhpBVnzqKpndDIXKwq80dGI=,tag:O5ZNdf93AquzJH6uzIdxpw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:oN9s7/ePd0gutn4Vh8bfgw==,iv:7LXKLRKFXnKhGJNHn8wZLtWFDY++Ibnoh/pGqW0O374=,tag:Jx+0yUCsfKMASexRhLKEbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZUdsblllVVNDUUdWYTNQ
            Rm1KaCtOdWxFRFE2dU1sb21INmVpLytPZlVVClZUbENaU0lCQ2FWblF6LytsVlRh
            WnpZQy93MTAwclFGOEpkQUlqZWVGNlEKLS0tIFBqV0M4U203S255bEtBV0xTOFVl
            czVnN2tEaVhTNnROK1lWU0FnMXE2VE0KlCWCoeQGVG9p6mKaAZXcJ39/pHnyBCNR
            4gT9CiABR8pTeVeLVlOnBXipURYTWxq5a/HUEBPZ9dJyF1zsggioEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-28T20:19:35Z"
    mac: ENC[AES256_GCM,data:WMAzFsGbrFby7UjZjvWMJsHk4QVPxMGUSFtTVzQKYN4Hfe04BCQl2dFgF2Py4Anwzh8STMmi/2uZZ1BFbGXTE2FpnqRVXbBVu8ljPIT9mF2QayI+ygbct5Dvt048tEQFVfxmzA2oTaTN++912BabdMTYtwqK2P/Y3xUE//NG/bc=,iv:x4cnCNNC121QClLCEKaLy/M8890KvlYCT8cwxyobLCY=,tag:faPZSfYX10x67JpZqxLVVg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
