kind: ENC[AES256_GCM,data:Oh7aj3OK,iv:/Qap94SD1VxOXLqVoKsAuVbQNEgpiJtVKnr4nNqYNyk=,tag:l6+V2xDvV7XXuzAHG9uAJQ==,type:str]
ansible_user: ENC[AES256_GCM,data:qpn+OZ49Hw==,iv:9jJ04yhzcMpDDTtvWv5UtQWTGDK9O/MVQnK1fW1r6Hg=,tag:haOz4WzAsddncLcsV8z9dw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:8mfUYwkgwIUmPUN5ry0T7g==,iv:KZd4pJUm5iS/QmXVeig253oNTuUzoYrYWf/RhvB4Qio=,tag:FesxGRi21MPwTDhOaV9+OQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzRklYTTI2L0hmRWVqS1JC
            UHFETjVsTFAxQ0ZZRjViaEFBSng2MWdRM0dRCkt3Q2c2QmtPdWNJTjFSQlZJck9C
            d1ZSVmtTM3ZyOExFZlE3bXR0ckZwVnMKLS0tIGlrWmVPZjAxWHdwZEUzZDEvb2VY
            aDhrQkRDRVpVSWFjOFl1YndTNjFzZ2cK2ED+AsH51dtBCu7+ygTdSLHypa5fGkn1
            QQgu6LhtPSTZESg0goB3YkVRz6rV/J9JvmMLvSGcV0ufa025G5Ebow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-27T18:06:52Z"
    mac: ENC[AES256_GCM,data:Km1Vj2FXNuAEvGizZqTaUM2AmjmD2+dpQHMjg1T4MNccoQ87597DTbz10/WxgGOtvCmKUAS9a7GroVhLhu2BsKhVqdaaSj/cXBCwJtboqpHTYUn61YofxyigYu3Dl7N4aIVf7e9EG8RdHMBGWQLISyf1zhulPAuPd0C/SLWuhBw=,iv:vkum4feEzMP7jv7WKrSJJW4kx0ESlstlX6Sr4V1C39E=,tag:I54auzdFbIor6nwiC6BXug==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
