kind: ENC[AES256_GCM,data:++WNQVa9,iv:Am/HyvuJ+LQUzQUJ7AlvG2UeNtW5bwKDpT7D5PiMqTE=,tag:mdWxHHwr39ChyJMMvAEX0w==,type:str]
ansible_user: ENC[AES256_GCM,data:QKFxkBUzkw==,iv:X12z4FpAQ/KbHbSHxhh31HBikganK7CFTx0qwJUuGNc=,tag:W+k6ypdYP6EbsoS/fSRNig==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:oBO+CD7ri0liQ8HAeBx+Fw==,iv:N5MpjzIN1pO+38Meup8YtOnIDEUQIL9pZ4kHs/kGTM8=,tag:PkuVSKgXWOGOUSTPiRbB1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZ2daTk91TG92MmYyVVRU
            MkJpakxpQUFIdWkxNkdDNGJEd2xVUk1KQzBJClBKU0RrWm5oRTZocjJpL2s5Tmtv
            TE5QdU1nbkhYQ1pqWlFNaGFMQzdXVkUKLS0tIHZZRXFzYkxIMDlsdk1pRndiMXdP
            OTUzKzZKZUpndEprNlM5dGt6dFJaMzQKpOphdd7MWLMlpkULR08YMtKb5mhWFVtU
            kCs52ojvX0x1cY3L9RxJyPJ/oDymIV0RO2+OZ3ONUuPaM6SBj13jRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-27T11:18:34Z"
    mac: ENC[AES256_GCM,data:L1Fs5t1A9oXtLLPCt1TLQIE7W45fGFT8bYx9hb1bj+OEmAl/lb7Yip9wLfRALxq/+3XLk6bB33YUOZ/3Zlf6w67TofdfAWhbL6lbCEmcKdSOZXiuXxhNUR4omOiTkVD+/TUniX1GGDzir1F1x8vKiucXolNwXAe344C4jFOwwmI=,iv:7BXekhRzCj7WSgfwhnp4i6FGjE6qo0JmwjP4Wotn+xw=,tag:lx1M2IoaKLv1HGxjwc8jgQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
