apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:O0e7EitCXPQl6AJ2a/j8MAvgpTBNgOvccjcgjPQTQMKwfAtF6oPgyw==,iv:YY1NoeGRovG5yokNU4HcsYad8m8vWZhua94vZgYltqs=,tag:nHYuBxTmlNbW2XnHojjpxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJT2MyRVpIZHd4R2V6VEV0
            dXA5Q05QSTVxKzNpaitLL0JGcHA0MUowTUdzCnlNb2VlY0FGdXFoKzJjUFBvb0Rv
            SURaTHBpZTVJOUxubVdXZDlGRGRTVzgKLS0tIERiQXI2VEhIdGw5ekQyWTZvYU9h
            aFVTL1RQeXZ5aXJncjloR25OeVZNakkKSJ5pPjBXY9u8RRvbHxLWM38F9sKRIjpd
            2qDhrsH8SIZW8oPKxq19i+dLPHT27C6pkZkJRE3W8d4o4rvxqaLruw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-29T07:42:00Z"
    mac: ENC[AES256_GCM,data:S0qP3dqO+u1AjH/eENnAD7eAe7OBfOVCqcxK8K2ACgig6PKRqDqftwp27hlgsSlv873WftOTZ9YtHr1WJgb67JS4Ic7ome+SyipNo6JvdFT5/QmjfNPlft3NyFHspbl7rB4xOp6DdY7Xg2eRDOxu7hE4wBTL8qvLFoNyHdjcUsc=,iv:X9YeMAbGggmdx2rwnUxwXpQU68uTlD9AbAHCKC1yZWQ=,tag:ToMT/UcSa7H3V0Yb+EPe/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
