apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:v0W+JknY4l38n99lCF6/y+PaeVblTycYjl/tpG+JT2+10tdYCSsOKg==,iv:AT5U7F6xEJP7ku6yEclDSPEkF8yCR8yjc3AZ72Q+Jj0=,tag:ThvFl2OHCcnLAXZ6F0SB6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVHdIeUJDOW1iTGcyZFhB
            MlRMOXZYOTBlZ0MzVUxHbkdHMHhQRS8wRkZFCithVEJ6TnJwdFdLRzVIRmxqcUtX
            YWdrYjVNVk9GUXE5N2FmaUZKVTZVcGsKLS0tIHpwQkx3dy9xK0k5aHhjb2lCbmdX
            RFBHSWpUbWNERUhsaVN5UTBzQXVyaHcKIkmOXawk6EZi8F/eeC1wL5fXVXBZdEEK
            YIKGlcoIkyI3byWAKHzFmkhUvfTJNP4mAbAZP5h7VMcZ7fqkUl4x0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-27T18:06:52Z"
    mac: ENC[AES256_GCM,data:snffgOeF0v8sDTfINRmVWJHeIqhVMKV5eo+IdZB21q/HnFa7a8z38gr+zkAr0ExIDJxssjnThqW6J5yI/Qq/ZK8FuKIMx4n8TBb9EoldK0nWaX0rHkavHTxrsVqpvI+v/MzrfbRaJKhMyMv7pTafH/c2n2C80foBzziCaLuJIA8=,iv:zEOT/mGqksih5lK3t0Q/qUiBLPwnvWt+XL0Obc0ENXg=,tag:Nbxt8yDB4osD4DS8tT410Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
