apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:vOPAFYypmyOt3jXSzGDTC8Td9GH/Lud4xojbakAyqRK5QwuAgYqjbQ==,iv:5NURrAXnHgJQNTcIgy2WZx3oqyNjind3OWikuwi32EU=,tag:gBhdLYpZN4w7MPVxIPkCcw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbUd5K2hNSnkvelUrblVW
            Z3FCNUxIUUVEMTUzalkwbVRTQVdjSFpwdTBjCnBOSVY2d3hXdDNWMEw2MkFWTnpw
            VVFtT1ViZU5kSVdvMUE2ekF6RHJVQUkKLS0tIGF1N00rL2dJOTczc0NJN0N3WjZM
            bWh5RG44bEVsWDZkYzg2WFBOSXZ3bTQKrVdNfhz24ldNhoAggplRFip6WPcN5ZiJ
            oCcFELt+9+kxzr64lbAvG33fc86frLGkw90DiSiwYfBG+yFaf0riNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-26T18:55:11Z"
    mac: ENC[AES256_GCM,data:lfJjlI9z/FVzCyZOtaBePlGW+yDr7Xcy5czMmqiOo+x2/G1nowybDjZwxa8HS5Isz7gCAoOptXLsTzmB3uPegZS+N7UM0Dzg4kRTPedM+6XOIFuApLS7rXH3AVE1Ngtlnem2dcnhOQwnivHqLakafpyiEqJGJs/GPoSgIoC9NgU=,iv:PKl4RhIebZguoDq90XWpN6jtSjngFr6F60/7n9l64K8=,tag:qA7QiN2HblzLZfypBhzEIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
