apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:LJ5VCO0FhtcLRkXdVedw8tWz2IIYR+m9pFTbkGf3ahxOwTzkmg==,iv:SAWB1YA9oZVoWE5xCk4PsUZvHTm+WMVV19Mo+IE3gQ8=,tag:8q3ieZrhAmmX1Qg/XGVPjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdWtoRWVqK21zKzVwM1RB
            Z01tQ3p5MEYrelJlQTZqT2tsTkxIMCtMdVU0CldFRWN1cmppUTFtbVZ4Rk9pM0ho
            RlMxOEJZcnRPb2x2STVHVWZTbnQraFUKLS0tIDU1bFhaSHBWUXh0UEhoeHJRNXI5
            U29Sa0U3em8yOWoxV1VJemR2N1hsbkkK9JVKbu6GIiu4bnst8N5GejYKsJwdmr/1
            NBQ7eCWQtC7WOa1yqgq0RUqieJXuQHmj04Advm8qB3YFSOYhGmiFVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-29T07:42:00Z"
    mac: ENC[AES256_GCM,data:XHUP5czvonmRRa9O8D4pPcpssEO3kXNoE92zDe+KqiABjchFDIqpoRGuSQPNuHbg1e9uLAd8S0RneqFigmzyYatNh4W+v5nIJedzMP6NcRZ8E/Uf5xUUR0nrcTWCwJFzxncPvCEJDSc6KsvUTi62xrIoJU9VyO9BB9SATrP6twc=,iv:xShNsfmXJ2aCeLx4oEQ58H2VeY894sXZ6s+vw/kEYbg=,tag:P2ub88THP+Zjz2I2I3GZxg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
