apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:Xvu1cuICpTk1NO/gt1ZHT4HmBwZsEic1/uoGXv2M/AVeTeZLkg==,iv:AplB6vGS3sR9Rl+oVf3So4ZFOmpWxgJHGPAUl7MNWZY=,tag:ctRffkJ7paLKFMVNcJ4NvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxY29VOTF0TXppSzh3My91
            cVhQbEttb1hVMTgxdVNvQlhJWTd5L1pSOWd3CnVPZkV1cG5vSytWRmtweHg1M0Rn
            YUY4YnU0cERkdVhJRUlMQ1JpSUd1ZGMKLS0tIDdEK2dQZFZJTmUxcW11bllsaVdt
            MTgrYm5HQ2hoVWM1NUs3eXNhMjNiVVEK/OpMXKop/J0Jeu7fcigDrzbKnO+kxViv
            yn1rW/4bOrE7za2Z4VzPBeyuimP5/rKuLoHIg065xUxF36m6fAp3Fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-27T11:18:34Z"
    mac: ENC[AES256_GCM,data:2pY0xOLVQE70tgwWZ2xrsDHUy7Ey2ClWPIEEYowK94rOmVb7KWhLOflxcjNmCc1quTJaAgGO88iCYsI5Vl0lejgcm3m4+U1EtJCknvBpt/lZh6/MmyxJSrfXPqV9U+DmV17Lyf/uxGr3GYR7TlMWsXChrRne/fTog27Sp+ROU9A=,iv:yMhCG73/7gsjCBU6l9yGEK2hhfknyRNkDI+pf2+8qPU=,tag:hcK2fvte77JE8h5lgwuLaQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
