apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:gUv2qoyhjUDWSqpImPOe9FmgQBl/YUdpdW5l+urnBKg7fNrW3A==,iv:ccI/h4w/cK/4NSbXBHgbRihTgjovX2884XKeLCvarIo=,tag:Vn7Zy6jQLmTfss1JrQPypg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNFZuUmZJekFneFEzdGQx
            RExNa1RxUnB1QjFtL0J4L3B4RjM4czZ6RkE4Ck9EOEh0dFljMTdBeDg1dkZTQUhl
            cWkxSmhuRldTVVQ1MHBBOWF0RlBnK1EKLS0tIFhUbTF6RDU3N2VPb0F1ZE9VUit4
            Y1p4VzJBUnFBbzRoWXlzTGQrTkx5ck0KCvATm3kqy5rSimi9fTSJ/fiSbyA2UepO
            CTj2mYESwKeHY/5Gd+suYJnQiEG9Qj6hxwnRptDEZt5cn2awMq0thg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-27T18:06:52Z"
    mac: ENC[AES256_GCM,data:reK2gkS4lNCD3t32tr27d/9iPEznZ5tQNlpZYhyAV6n44Hhp6FpuLImyAjVLdwfdxXm1p9z/JuOhVg4fQVMNZAdWvOkE+z+T+R516k/twDmp0STtus6jTMGNyvKSRQj4jJrG7tRxGdDKXBkw0odGtUp6h9bjvrmXnEIYYnjpBI4=,iv:q/qkqjtnhcLWp/9FaBCKtGbCwtR/ZhqjmiLxzUl7Nws=,tag:ZsmVC/ehy8Lezwo44CoQ9w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
