apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:KEVyFIi31MxbunarMOvCzIBALtKACdXo,iv:z/TJ23BF2u65+y0+BwqylnFheCbGiKX+e+0UtEBbcnI=,tag:AisS1YcEwrgCTs5PFWWdhw==,type:str]
    api-key: ENC[AES256_GCM,data:c3bLSRpXc/9oBfkxFMzI4rYd5rEg5s4q+NRbS1iOb3dcvB9V0Q==,iv:0zYqHQhOkAoSz1kuWtqPw+vPRo7wwFeQbEsN3dCIvCE=,tag:rFISDQcug5iBZLOY3kmGDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZzhwRmRBbXhoNEJlK3lW
            ai9zbjNYbWVyaGtiMThiSDErSHFBTG5qOEZjCnlPR0JPTXVac2k5aVdydm9BNlVG
            aVUwM1dSL0lYVWNxc1lHY1NvQWMyODAKLS0tIDZ6SGg5NkQ2SlgrQlRCL0R4ZjlV
            ZVFGL1IwbExyNk5jdjlva04zT2NZUXcKSotbJUzaJFgPuxgKs4fmbrDvYN+/8CSq
            POB1ONj1ckvSUc2jmpgZFuzObfQc6GHGpktDkUL8liQHME58PxjhUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-26T18:55:11Z"
    mac: ENC[AES256_GCM,data:nFXjDsBOAaXxCMeVaJjvgkmNKxtXfz+6hALIKncMx5t8wF6oUY0xHbq7gM+eiaX+B6WV/jpPwhj6oUzcsSHJDKy2rXwuL9KDE+KQXwJHvagWfwp5zJ9f6tJFnYjqvyDqS3Gixibgi3DQLnhTL0aUBB65cO00KlXwEp+8RgYQRTE=,iv:Fywt3q5wqxgAmYzqRJbMLZ5L5A2QwZK1u8fQZbbn0V0=,tag:3+tLzMFLyKVY7lBFUQJtBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
