apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:GnELQZF3HC0+rGQAb9eGBLFOCdSM0xPs,iv:uDjTgY13HGvgQXZjdg9S9sB0xFR4NLwvusfllvDM+gM=,tag:YI0mu91nEBybAgdY5fXuPw==,type:str]
    api-key: ENC[AES256_GCM,data:U9zJ1ivOpuqp9Z8Oe2y2BmvFnYRvoAT3cCZDtFFo0r/FwapSWw==,iv:UAKygT/OHAtshNUXWD3S8gkSsx3iAX/023Hs35U75RU=,tag:VlJC1zb3YjeiUemNSY4MHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzb3dTd0xhV3JSWm9yc0I2
            dVg3ZG5aSmZNZ2RzR0RCUkFLV21FR2xzTmhJClJScExMTHhzZ3VWS01PTlJSbFlq
            aEpRMy9odzgvNk9lc0E2VGYzc21SRWcKLS0tIEUwMlZ4aURHOGlxdVZuSzZuNTFu
            ZVczQ21zR05OdU9RVk9mM0hDUmNlTmsKUoZ7//PllTGdQbe7Y2P6s3Z2ZKO39oCq
            VKGNVwRXjDpnqFh5xudWRIGEC7VxeMduELgV6fpJnkr01WtSwtyIkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-27T18:06:52Z"
    mac: ENC[AES256_GCM,data:fIz0yySLkEdkbAUSTB2bK4TWG80hxz0v88RfajZbic1mpm9Ax7EfMMJdTjkIGxql16tdA9SgD7aHTdcRa3mpX1dqyOjmBhzpk6s/jg0xK/uPp+GQiFLurynNuT9XOrNhKr8+7NRUPxyFJm8IHS/7ocJXmJvSCZWiUn+ZKZ6E0Sg=,iv:L/5zrVrH19uXQKqScu4/uQhJ9wykUS1jWY3S8l3LzN8=,tag:nveq2/1iLdDKKu9oSYiz/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
