apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:sQXYTg1X9i6M3xilXgWSTlAia0BbSeOr,iv:/7jgRcCdJvU1Ekc9QY++efDmnJKy1/SSLsG5MD0zU3A=,tag:90i+3XS99nbYC93F9QNq5A==,type:str]
    api-key: ENC[AES256_GCM,data:HRAQRijqLwwkb8Niw5xKR+1or83aaDQz0BiGRO9wkFLQw+riFg==,iv:BQtCzgPJQ6WGWQ2j2vD40dat1JLY3Iu80JRVozr/JlQ=,tag:gmZEhLQLMzCYclKmy1ovgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5L1pjdWZnWVFMMktnaXJL
            RnY5Wkx2T3hWOUhLSlhkU2h6ZW9EWUdMZjBnCjZEb2ZNb2thN0phRCtoaHRHSDJw
            U1VEQlBrREszbkxGbXk5ZlQ3WUFuZ0kKLS0tIC8xZU5iZU5QckV4azEreDM5dFZP
            djNyNVlhN2FhZjFVNmd1aUpqZTdiRncKfsslLcq5wSitZpnoRLBV8SMY+YkMhK9A
            fFgw/j1a9TYDQRLU+dUJ/8RTaaPC9zan0NrZFoPRFlMY1sjfGuS2Vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-27T11:18:34Z"
    mac: ENC[AES256_GCM,data:53nnenmpxoFBhzwE4kzA3v10/r/IkSZdZzj7qy0yJK22JJLuakibQswTvQhSweLvkHDCKNWor2mt2RaN05G7Mb9qUiD/NEEIjLnbNH+FR0GxYl0sa3NiQ/xx85t9pP2gwkKADHJzrc6XjnbPloqH+CAu4YFmYTILplejDizwE+Q=,iv:tPsCiaV0Q50YXYHCA1hkyPlBfYppVoYpVId5r3IAl+0=,tag:1+7mOzKhLtp6ZII3m3+x+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
