apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:Xsb/wpCn+u5mM3MSLAVgf1V6C+fnYb0sRS+7HviYIOCfJILdqF5QlK1vYkzExNtBbm0phld4AgBfW66o,iv:DOQ9LuEHOlJLiTuGzCcDaiz1VFdXLlVh4/yAq44rLCA=,tag:X5E2PKTQ6AySZcSNihYSlw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQmEyRjh2NjRlV3U0N3JS
            TUJJWFV1Q2V4Rlh5N0paTGNOQXdzLzZGNFN3CnpJUnpJVWVMMnpCYmE2Zm9BWnA4
            WUZmMkRtSVN4dmplR2lNNDNtd3BBYTgKLS0tIGpva3pLL0VYNGZyM21qZWpkSnRh
            UTc1aHhPZ2QwOE9udlZYYUxMc0JJblEK2TonfK5njqhU4tIwvbs3cu284lenQMT/
            5sBLNIHMXBKE58NnZZ/FTtVlhfyKia3Afz3U2ouYXzOz+HHRuYK8Jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-27T18:06:53Z"
    mac: ENC[AES256_GCM,data:NV/qXf2vJTMFM1EvuTRyIFCtNbN9lY1oTfvflUvNI4VRFrDDWCG7ekxMoJ9gUi8juVY1norYqauXAqcMVhmvgp4Mjnd1HZwBw/5SPNj/q4yrsqsvJ9yxlh3Nx7MLe8F2lG3OGEmCrpjph/whzWQ/JvzMZlBjSHr92W3FLc9DeRY=,iv:aCjsZf5SiytPc2sJ/AAu43U2TU4h8H1SqmlRS/ZtEIE=,tag:4EDQe8ZtkMSUSmlN/3vIfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
