apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:zHcsyDHELwWDiPokVjNXu59XCAwquyO6BxTRJlIaHUtbU4s21es93VMU+Z7EP1s5v+AUBQ8MZbw2wrrE,iv:SXufFg83li/iXX+OEA7R5xD3Bu0USN9LCL778+lAImY=,tag:PIjbxujHNE95nvPduekGHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMTE4WTUyWjlseWNxK1R1
            Q1oxOGN5ZWVld3dqbllXaXU2NEcxaTNvSFM0CkRLWEpNcUNZaUdhNTVHYUh4bmRY
            TXJVbUNraXA5WVF3U0hUcWlicjBXZVUKLS0tIHJTQ0xJMzVVZFR5QmJYdTVMK0pL
            WWlXNElMVCsvcU01K1FNWU5sZUo0ZVUKqCS9D0Tz4GTFyYu6Q2g/9a2W628xirPj
            CKXA9Y9ItSuderWxtDWC5pgnDlz9qx8irPXYf8iAQ+MoN/FSOMcAFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-29T07:42:00Z"
    mac: ENC[AES256_GCM,data:qm34lmiACHvMQwyPAAwmhmE+eLk1SbQc6e3rGWRev36NPJZKmdj6SQJ3WIzOAvBqzS0nz9l2hkF1muVP7xdErNwMBqNXJ43lBravHmtdAVxGarUoWxayCHDyFTlUxoVL2Ga1VXlHFkQvs0O843lEO506lWMKy3mlJhLyLaUqDtI=,iv:g0JlkamceNaIBQxMmXR+1kYtLeJBq+aVA6fOuw3QDC0=,tag:0aM2fuu7EAUw4qLIQ/SGrA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
