apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:BfXgy/1CY/PEa+U1pWOaxRyN4ODZr2IwPsA7sqwWuHLnjTehRjYAccANlyXgOEajkhmJqKkPADHOlbU2,iv:jxWB+XN4Jq9UI0YCjCk7sCcO+RPJycAb9MkF+BD5WW0=,tag:eKODkOzZ4CpUtMvoUnVbIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSVFYR1p4RlBRdEZKT2Fo
            K0NmTDExdkx3bHVOWHNnUGxZa0JNRVBJenlNCjl5MUoydHBuc2g2SmFVdzR1RXhG
            aFFIWTJ1ckZsQ3E1OURPYlZGUlRld1kKLS0tIEhoc2FRY2MxYjVkRXFrN2dXM1Ev
            YWtIZWkwSXc5T2I1a2luakNackx3c3MKugPhks4MB9b1CL68f55vyGbFFBHPKPBl
            VrPus8AzsG0/zPmM77o1tgWX8M+czhfBziRZ1qrIBxhMyqBEr3v3uQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-28T20:19:35Z"
    mac: ENC[AES256_GCM,data:dn8jBPVycS9digM7AtMfK79d4srf8y6zOiI5/bTFn2MQNNjaWySMtpterGYBwVtveCVwaVVGHVHMXf9j6ijaeIbolRtXrrWRUghgJaOagdbdoxj9V5lfUht+IrDIYxFlTbbnBbRfSWfX2oGwlb3PS7N2HT0YmE/gDex/RKEyyZ4=,iv:VWLxJYwomXDp//Xhb6Nq93ToUrCWaCuKrwBTWxtPHvI=,tag:FzZc4gaF7gEfaezAae/veA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
