apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:JGk1a3nY3TLf3Q==,iv:20Pj+xPvBhF7rAnbaGQhEIk63iZ0aOvPM96e9J8STdI=,tag:CPpIHNjffFFSHngqQ2km7Q==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:weJAcnERYFnG5scKvluL7cbqdLh+PEpz,iv:GcGzLVdhGqQmclnD2yxM66HVJ7C+p+TX1ijmE3Oso6g=,tag:RLG498XT73uKhZtaYHPL5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBheFV3cWJBeXBkcG9wTkYw
            Y0Y3MXRLaEJkV2I2SkJwblVUOGZncmNGMkNRCkI3N1lhSlpqL2o0L2t0bkJSMDNM
            cS9qSDVtcEYxVzNIbWJmU2NrMWREbWcKLS0tIDAzZzFNVkJsZjN4aURYZU8xN1Ex
            M1E5cjROOWpWakR5OWY1TTVoRWMxY0kKm/Yo1ndBHLxwUYdVHQvsnfB6Gf7twMXb
            57PvzGWN2cZ4/6wvplNkrdKjyf9fOPh5euiCckFEBeYPyFpsMxjppg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-27T18:06:52Z"
    mac: ENC[AES256_GCM,data:vjg01FD92oBV7QjJqLYD8KzgVWGCz+mhpmjpIwzH3xUyW1InxoOsHqHDBM7lUuG8uBoOo8mPJZPapT/m+Meo8mRb3rAaulS+xwV4QKPDUDlcgc/xsXZkt2bBZ/UP9cbgY+DRVq9/hhljDBD7Uutn5xZGR7B26XurC/2JmyDQ5q8=,iv:2fa+ASe519Rqdi7vyTdGab3Qk54/K7MiJ2YSIvaVAdA=,tag:SRk1DdKEqvNkIq5zEWKBKA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
