---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Warsqaw"
  KUBE_VIP_ADDR: "192.168.10.20"
  METALLB_LB_RANGE: "192.168.10.100-192.168.10.190"
  METALLB_K8S_GATEWAY_ADDR: "192.168.10.100"
  METALLB_INGRESS_ADDR: "192.168.10.101"
