apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:+Eq6umpTQCE+ng==,iv:xXuFuy9LR1/jSoudOFkN1NkqIJDdioMUZg5+H0x5d98=,tag:DgHPKk0lNUINDYxlsW1yVg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Z6Hb5rjESfN+sJL3Q63hPaX9AiMFnise,iv:T3JLeK/2qdhurKLjT8c7sB6KzrEudcwA+ePWL27qWdg=,tag:VS5B37vWBgtT7i+bMiIjAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZaEE4ZHRRZGQydHV6Rm1v
            bmovOUtuc3paNUtscUtmRGJRNWp1ZWZtcEc4Ck9ESHl5czRDdlRvWXNXWmYxY0Vu
            UXNubEM2UENzaVJ0eFJpZUZhUXZEd0kKLS0tIDVkaUJKYVNOUlloMFJpbkRWZ1cz
            cmxTWnh5bkN5UUhFU2t0eWRhRFRYSzQKIxaBxQARdoEVG+WFoKg5BPtJrGQYHuJY
            toG2j3zW+Sqw8Q389wul8LDyMmDVwILayyNbh18oTLsKGc8Mnpb7ZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-26T18:55:11Z"
    mac: ENC[AES256_GCM,data:72igH06IJTz3i6Ympcyhr2l2XwQydROAmCy+O4XHWmy9t9MwOv6jkKB7QZOhTGZbtRaKxNI9W1ckK6XSFuya8K+dJk/uyDyJ4y4YdX6KPKe1GbfyeZHGnaKnK8AVIz57c6uZj954Au0LH8zV4+17m8BMSnCwPxIHYp5+1Oy6pPA=,iv:sDSb0qjyW4crE0i30KmrZZZMj0IRS2Z18asR5FaJqgE=,tag:KTV1Yy48oIN9QNgT7fFfBA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
