apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:JABFhslnfcxchA==,iv:Hi1QwNHWgsUfBhioXKiljg95tuyXi05uAA1qzRkUsPw=,tag:AoNUEXM0tZpK794P6AoQCg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:k69NOVerIqobuRuAE6/9ORbs5AaK0K2R,iv:eve2OZSC6gUoG7JA+htGDaQ4NRwQMrYEtAD9k4r3Eas=,tag:+Ut+F4dSUZbaHQ7kzqa0HQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdklsd74x86csjrpwld4uhwn9244wyxsyta60wv34pcdlsdnjvrspgf3cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTWpwdU41WEpXVkVGeW5r
            UVRYVXlDcWlaQmM2MlF5NWVwY3BuQWJHNGlBCk12SG9QV1YvY1ZsM3lkMk1xcW4r
            TjFpU3pnWkRVWVdRTGVrWGxzRGFpU2sKLS0tIFRsOEZITTNUblVVQWpsNTA1VUJV
            TnVsR3hrMkRaZEl6ZG5aWDMvRm9nUEkKCFo6jBNd3VA9+CRZ9pQxntoTf6komkrS
            +owICsNsXd7HTT7a58+9R/i9p+gRdi8Ja00S9IWQ5GupDnfPWtRcGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-28T20:19:35Z"
    mac: ENC[AES256_GCM,data:/Iy+Yvf3rwXzt2BL5dGWCEe477XZrTdXAi8lTKYL0mIeTii6JMCyz42qmqvhOy2Hs1LGAZpdE4jxHz3N4YqN+OOPM0CDmF1yLt71vwferaa9CZr1YOjsSFt8VBPzw4dGHQq5A8QIJzPxhUcmnGNtIkhTxBq/IM7jkqTy063vmlQ=,iv:yg3DoOUXz1UotwE/Izm1rY9pI7ISZ/iJxllViczN2/o=,tag:KJ/GHCE++KGDU8VqZTs0cg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
